" Powerline
python3 from powerline.vim import setup as powerline_setup
python3 powerline_setup()
python3 del powerline_setup

" Pathogen
execute pathogen#infect()
syntax on

" Indentation: 2 spaces
set et ts=2 sts=2 sw=2

" Make catkin workspace
nmap <leader>m :!/home/vagrant/catkin_ws/make.sh<cr>

" Highlight searches
set hlsearch

" Colorscheme
colorscheme desert
