" Powerline
python3 from powerline.vim import setup as powerline_setup
python3 powerline_setup()
python3 del powerline_setup

" Pathogen
execute pathogen#infect()
syntax on
filetype plugin indent on

" Indentation: 2 spaces
set et ts=2 sts=2 sw=2

" Close YCM documentation on exiting insert mode
let g:ycm_autoclose_preview_window_after_insertion = 1

" Make catkin workspace
nmap <leader>m :!/home/vagrant/catkin_ws/make.sh<cr>

" Highlight searches
set hlsearch

" Colorscheme
colorscheme pablo
