# Vi keybindings
bindkey -v

# Antigen
ANTIGEN_MUTEX=false
source "$HOME/antigen.zsh"
antigen use oh-my-zsh

# Oh-My-Zsh plugins
antigen bundle dirhistory
antigen bundle history
antigen bundle last-working-dir
antigen bundle screen
antigen bundle vi-mode

# Zsh-Users plugins
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting

# Oh-My-Zsh theme
antigen theme https://github.com/caiogondim/bullet-train-oh-my-zsh-theme bullet-train

# Finalize Antigen
antigen apply

# ROS
source /opt/ros/melodic/setup.zsh

# Catkin Workspace
local catkin_setup="$HOME/catkin_ws/devel/setup.zsh"
if [ -f "$catkin_setup" ]; then
    source "$catkin_setup"
fi

# Turtlebot 3 Model
export TURTLEBOT3_MODEL=waffle_pi

# Color ls
alias ls='ls --color=auto'

# Snow color scheme
[ -n "$PS1" ] && sh ~/.vim/bundle/snow/shell/snow_dark.sh
