# Vi keybindings
bindkey -v

# Antigen
ANTIGEN_MUTEX=false
source "$HOME/antigen.zsh"
antigen use oh-my-zsh

# Oh-My-Zsh plugins
antigen bundle dirhistory
antigen bundle history
antigen bundle last-working-dir
antigen bundle screen
antigen bundle vi-mode

# Zsh-Users plugins
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting

# Oh-My-Zsh theme
antigen theme https://github.com/caiogondim/bullet-train-oh-my-zsh-theme bullet-train

BULLETTRAIN_PROMPT_ORDER=(
  time
  status
  custom
  context
  dir
  screen
  virtualenv
  rust
  git
  hg
  cmd_exec_time
)

# Finalize Antigen
antigen apply

# ROS and catkin workspace
local ros_setup='/opt/ros/melodic/setup.zsh'
local catkin_setup="$HOME/catkin_ws/devel/setup.zsh"
if [ -f "$ros_setup" ]; then
    source "$ros_setup"
    if [ -f "$catkin_setup" ]; then
        source "$catkin_setup"
    fi
fi

# Turtlebot 3 model
export TURTLEBOT3_MODEL=waffle_pi
# Gazebo VPN fix
export IGN_IP=127.0.0.1
# Default to Qt5
export QT_SELECT=5

# Color ls
alias ls='ls --color=auto'

# Snow color scheme
[ -n "$PS1" ] && sh ~/.vim/bundle/snow/shell/snow_dark.sh
