#!/bin/bash
MAKE_C=~/unified-resilience/catkin_ws/src/ls_slam/CMakeLists.txt
SLAM2_C=~/unified-resilience/catkin_ws/src/ls_slam/src/ls_slam2.cpp
SLAM_C=~/unified-resilience/catkin_ws/src/ls_slam/src/ls_slam.cpp
LOCA_C=~/unified-resilience/catkin_ws/src/ls_slam/src/pf_localize.cpp
PART_H=~/unified-resilience/catkin_ws/src/ls_slam/include/ls_slam/particle_filter.hpp
PART_C=~/unified-resilience/catkin_ws/src/ls_slam/src/particle_filter.cpp
COMM_H=~/unified-resilience/catkin_ws/src/ls_slam/include/ls_slam/common.hpp
COMM_C=~/unified-resilience/catkin_ws/src/ls_slam/src/common.cpp

vim $MAKE_C -c "tabedit $SLAM2_C | tabedit $SLAM_C | split $LOCA_C | resize 15 | tabedit $PART_C | split $PART_H | resize 15 | tabedit $COMM_C | split $COMM_H | resize 15"
